---
- name: Set OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yaml"

###
# Kernel configuration
###

- name: Sysctl net.ipv4.ip_forward = 1
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_file: "{{ config_file_sysctl_ipv4 }}"
    sysctl_set: true
    reload: true
- name: Sysctl net.ipv4.conf.all.forwarding = 1
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.forwarding
    value: "1"
    sysctl_file: "{{ config_file_sysctl_ipv4 }}"
    sysctl_set: true
    reload: true

- name: Sysctl net.ipv6.conf.all.forwarding = 1
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    sysctl_file: "{{ config_file_sysctl_ipv6 }}"
    sysctl_set: true
    reload: true
- name: Sysctl net.ipv6.conf.all.proxy_ndp = 1
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.proxy_ndp
    value: "1"
    sysctl_file: "{{ config_file_sysctl_ipv6 }}"
    sysctl_set: true
    reload: true
- name: Sysctl net.ipv6.bindv6only = 1
  ansible.posix.sysctl:
    name: net.ipv6.bindv6only
    value: "1"
    sysctl_file: "{{ config_file_sysctl_ipv6 }}"
    sysctl_set: true
    reload: true

- name: Add the ipv6 kernel module
  community.general.modprobe:
    name: ipv6
    state: present
    params: disable=0
    persistent: present

###
# Network configuration
###
- name: Install networking packages
  ansible.builtin.package:
    pkg: "{{ item }}"
    state: present
  with_items:
    - "{{ network_packages }}"


- name: Dhclient6 configuration
  ansible.builtin.template:
    src: dhclient6.conf.j2
    dest: "{{ config_file_dhclient6 }}"

- name: Default network configuration
  ansible.builtin.template:
    src: files/interfaces
    dest: "{{ config_file_network }}"
  notify:
    - Restart networking service

- name: Create network interface file for {{ dedibox_kvm_host_phys_iface_name }}
  ansible.builtin.template:
    src: phys_iface.j2
    dest: "{{ config_dir_network }}/{{ dedibox_kvm_host_phys_iface_name }}"
  notify:
    - Restart networking service

- name: Create network interface file for {{ dedibox_kvm_host_bridge_iface_name }}
  ansible.builtin.template:
    src: bridge_iface.j2
    dest: "{{ config_dir_network }}/{{ dedibox_kvm_host_bridge_iface_name }}"
  notify:
    - Restart networking service

- name: Create iptables rule file
  ansible.builtin.template:
    src: rules.v4.j2
    dest: "{{ config_file_iptables }}"
  notify:
    - Restore iptables configuration

###
# Hypervisor configuration
###

- name: Install libvirt packages
  ansible.builtin.package:
    pkg: "{{ item }}"
    state: present
  with_items:
    - "{{ virt_packages }}"

- name: Apparmor configuration
  ansible.builtin.template:
    src: TEMPLATE.qemu.j2
    dest: "{{ config_file_apparmor_libvirt }}"

- name: Get shell user
  become: false
  ansible.builtin.command: whoami
  register: shell_user
  changed_when: false
- name: Adding user {{ shell_user.stdout }} to group libvirt
  ansible.builtin.user:
    name: "{{ shell_user.stdout }}"
    groups: "{{ virt_group }}"
    append: true
