---
- name: get shell path
  shell: "grep -m 1 -e '/{{ shell_default }}$' /etc/shells"
  register: shell_path
  changed_when: false

- name: get shell user
  become: false
  shell: "whoami"
  register: shell_user
  changed_when: false

- name: "change {{ shell_user.stdout }} shell to {{ shell_path.stdout }}"
  become: true
  user:
    name: "{{ shell_user.stdout }}"
    shell: "{{ shell_path.stdout }}"
  tags:
    - shell_update
