---
- name: Get shell path
  ansible.builtin.shell: grep -m 1 -e '/{{ shell_default }}$' /etc/shells
  register: shell_path
  changed_when: false

- name: Get shell user
  become: false
  ansible.builtin.command: whoami
  register: shell_user
  changed_when: false

- name: Change shell to {{ shell_path.stdout }}
  become: true
  ansible.builtin.user:
    name: "{{ shell_user.stdout }}"
    shell: "{{ shell_path.stdout }}"
  tags:
    - shell_update
