---
- hosts: all
  vars_files:
    - "inventory/os/{{ ansible_os_family }}.yaml"
  become: true
  roles:
    - role: generic
      tags:
        - generic
        - init
    - role: dotfiles
      tags:
        - dotfiles
        - init
    - role: shell
      tags:
        - shell
        - init
  tasks:
    - name: "[DEDIBOX] Set-up bind for Debian"
      import_role:
        name: bind
      when:
        - "ansible_facts['os_family'] | lower == 'debian'"
        - "'dedibox' in group_names"
      tags: [ dedibox, bind ]
    - name: "[DEDIBOX] Set-up libvirt for Debian"
      import_role:
        name: dedibox_kvm_host
      when:
        - "ansible_facts['os_family'] | lower == 'debian'"
        - "'dedibox' in group_names"
      tags: [ dedibox, kvm ]


    - name: "[DN42] Set-up NSD for OpenBSD"
      import_role:
        name: nsd
      when:
        - "ansible_facts['os_family'] | lower == 'openbsd'"
        - "'dn42' in group_names"
      tags: [ dn42, nsd ]
    - name: "[DN42] Set-up bind for Debian"
      import_role:
        name: bind
      when:
        - "ansible_facts['os_family'] | lower == 'debian'"
        - "'dn42' in group_names"
      tags: [ dn42, bind ]
