---
- hosts: all
  become: true
  roles:
    - role: generic
      tags:
        - generic
        - init
    - role: dotfiles
      tags:
        - dotfiles
        - init
    - role: shell
      tags:
        - shell
        - init
- import_playbook: gateways.yaml
