---
- hosts: all
  become: true

  pre_tasks:
    - name: "Include OS-specific variables"
      ansible.builtin.include_vars:
        file: "inventory/os/{{ ansible_os_family | lower }}.yaml"
      tags: always

  roles:
    - role: generic
      tags: [generic, init]
    - role: motd
      tags: [motd, init]
    - role: sshd
      tags: [sshd, init]
    - role: dotfiles
      tags: [dotfiles, init]
    - role: shell
      tags: [shell, init]

  tasks:
    - name: "[DNS] Set-up bind for Debian"
      ansible.builtin.import_role:
        name: bind
      when:
        - ansible_facts['os_family'] | lower == 'debian'
        - "('dns' in group_names) or ('dn42_gw' in group_names)"
      tags: [dns, bind]

    - name: "[DEDIBOX] Set-up libvirt for Debian"
      ansible.builtin.import_role:
        name: dedibox_kvm_host
      when:
        - ansible_facts['os_family'] | lower == 'debian'
        - "'dedibox' in group_names"
      tags: [dedibox, kvm]

    - name: "[DN42] Set-up dn42 services"
      ansible.builtin.import_role:
        name: dn42
      when:
        - ansible_facts['os_family'] | lower in ['debian', 'openbsd']
        - "'dn42_gw' in group_names"
      tags: [dn42]

    - name: "[DN42] Set-up dn42 auto-peering service"
      ansible.builtin.import_role:
        name: dn42_autopeer
      when:
        - ansible_facts['os_family'] | lower == 'debian'
        - "'dn42_gw' in group_names"
        - "'nl-ams1' not in inventory_hostname"
      tags: [dn42, dn42_autopeer]
