---
- hosts: all
  vars_files:
    - inventory/os/{{ ansible_os_family | lower }}.yaml
  become: true
  roles:
    - role: generic
      tags:
        - generic
        - init
    - role: motd
      tags:
        - motd
        - init
    - role: sshd
      tags:
        - sshd
        - init
    - role: dotfiles
      tags:
        - dotfiles
        - init
    - role: shell
      tags:
        - shell
        - init
  tasks:
    - name: "[DNS] Set-up bind for Debian"
      ansible.builtin.import_role:
        name: bind
      when:
        - ansible_facts['os_family'] | lower == 'debian'
        - "('dns' in group_names) or ('dn42_gw' in group_names)"
      tags: [dns, bind]
    - name: "[DNS] Set-up NSD for OpenBSD"
      ansible.builtin.import_role:
        name: nsd
      when:
        - ansible_facts['os_family'] | lower == 'openbsd'
        - "('dns' in group_names) or ('dn42_gw' in group_names)"
      tags: [dns, nsd]

    - name: "[DEDIBOX] Set-up libvirt for Debian"
      ansible.builtin.import_role:
        name: dedibox_kvm_host
      when:
        - ansible_facts['os_family'] | lower == 'debian'
        - "'dedibox' in group_names"
      tags: [dedibox, kvm]

    - name: "[DN42] Set-up dn42 services"
      ansible.builtin.import_role:
        name: dn42
      when:
        - ansible_facts['os_family'] | lower in ['debian', 'openbsd']
        - "'dn42_gw' in group_names"
      tags: [dn42]
    - name: "[DN42] Set-up dn42 auto-peering service"
      ansible.builtin.import_role:
        name: dn42_autopeer
      when:
        - ansible_facts['os_family'] | lower == 'debian'
        - "'nl-ams2' in inventory_hostname"
      tags: [dn42]
