---
- hosts: all
  vars_files:
    - "inventory/os/{{ ansible_os_family }}.yaml"
  become: true
  roles:
    - role: generic
      tags:
        - generic
        - init
    - role: dotfiles
      tags:
        - dotfiles
        - init
    - role: shell
      tags:
        - shell
        - init
  tasks:
    - name: [DN42] Set-up NSD for OpenBSD
      include_role:
        name: nsd
      when:
        - "ansible_facts['os_family'] | lower == 'openbsd'"
        - "'dn42' in group_names"
      tags: [ nsd, daemons ]
