---
- name: reload nsd database
  command: "/usr/sbin/nsd-control reload"
  become: true

- name: restart nsd
  ansible.builtin.service:
    name: "{{ nsd_service_name }}"
    enabled: yes
    state: restarted
