---
bind_primary_zones:
  - zone_name: nbsdn.fr.eu.org

dedibox_kvm_host_dhcp_duid: "***REMOVED***"
dedibox_kvm_host_ipv6_block: "2001:bc8:3feb:100"
dedibox_kvm_host_phys_iface_ipv4_address: "51.15.171.197"

dedibox_kvm_host_ipv4_port_mapping:
   - source_port: 223
     destination_ip: 192.168.0.3
     destination_port: 222
   - source_port: 80
     destination_ip: 192.168.0.4
     destination_port: 80
   - source_port: 443
     destination_ip: 192.168.0.4
     destination_port: 443
