---
- name: restart networking service
  ansible.builtin.service:
    name: "networking"
    state: restarted

- name: restore iptables configuration
  community.general.iptables_state:
    state: restored
    path: "{{ config_file_iptables }}"
  async: "{{ ansible_timeout }}"
  poll: 0
