---
- name: Install a base set of software packages.
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ generic_packages }}"
  tags:
    - generic_packages

# Render requested files
- name: Install a base set of files
  ansible.builtin.template:
    src: generic_file.j2
    dest: "{{ item.path }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('wheel') }}"
    mode: "{{ item.mode | default('0644') }}"
  loop: "{{ generic_files }}"
  tags:
    - generic_files

# Populate the known_hosts file
- name: Create the root ssh directory
  ansible.builtin.file:
    state: directory
    path: "/root/.ssh"
    mode: "0700"

- name: Ensure github.com is a known host
  ansible.builtin.lineinfile:
    dest: /root/.ssh/known_hosts
    create: true
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -q -t rsa github.com') }}"
    regexp: "^github\\.com"
    mode: "0600"

- name: Ensure gitlab.com is a known host
  ansible.builtin.lineinfile:
    dest: /root/.ssh/known_hosts
    create: true
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -q -t rsa gitlab.com') }}"
    regexp: "^gitlab\\.com"
    mode: "0600"
