---
- name: Set OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yaml"

- name: Download the headscale deb package
  ansible.builtin.get_url:
    url: "https://github.com/juanfont/headscale/releases/download/v{{ headscale_version }}/headscale_{{ headscale_version }}_linux_{{ headscale_arch }}.deb"
    dest: "/root/headscale.deb"
    mode: "0644"
    checksum: "{{ headscale_checksum }}"

- name: Install the headscale deb package
  ansible.builtin.apt:
    deb: "/root/headscale.deb"
    state: present

- name: Create headscale configuration file
  ansible.builtin.template:
    src: config.yaml.j2
    dest: "{{ headscale_conf_file }}"
    owner: "{{ headscale_owner }}"
    group: "{{ headscale_group }}"
  notify:
    - Restart headscale

- name: Enable service headscale
  ansible.builtin.service:
    name: "{{ headscale_service }}"
    enabled: true
