---
ansible_become_method: sudo

root_group: root
sudo_group: wheel
default_shell: /bin/bash

dotfiles_files_root: []
generic_packages:
  - smartmontools
  - python3
  - python3-apt
  - vim
  - man
  - tmux
  - tcpdump
  - dnsutils
  - htop
  - strace
  - git
  - tig
  - curl
  - wget
  - rsync
  - make
