---
ansible_become_method: doas

generic_files:
  - path: /etc/installurl
    content: https://cdn.openbsd.org/pub/OpenBSD

root_group: wheel
sudo_group: wheel
default_shell: /bin/ksh

dotfiles_files_root:
  - bash/profile
  - ksh/kshrc

generic_packages:
  - python--%3.11
  - bash
  - git
  - tig
  - rsync--
  - vim--no_x11
  - rtorrent
