---
- name: Set OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yaml"

- name: Install snmpd packages
  ansible.builtin.package:
    pkg: "{{ item }}"
    state: present
  with_items:
    - "{{ snmpd_packages }}"

- name: Create snmpd configuration file
  ansible.builtin.template:
    src: snmpd.conf.j2
    dest: "{{ snmpd_conf_dir }}/snmpd.conf"
    owner: "{{ snmpd_owner }}"
    group: "{{ snmpd_group }}"
  notify:
    - restart snmpd

- name: Download distro
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/librenms/librenms-agent/master/snmp/distro
    dest: /usr/bin/distro
    mode: '0755'

- name: Enable service snmpd
  ansible.builtin.service:
    name: "{{ snmpd_service }}"
    enabled: true
