---
dn42_config_repository: "git@github.com:hcartiaux/dn42-as4242420263.git"
dn42_config_directory: "/etc/dn42-as4242420263"

dn42_ownas: "4242420263"
dn42_ownnet: "172.22.144.160/27"
dn42_ownnetset: "[172.22.144.160/27+]"
dn42_ownnet_v6: "fd28:7515:7d51::/48"
dn42_ownnetset_v6: "[fd28:7515:7d51::/48+]"
dn42_linktype: "34" # encrypted with safe vpn solution with PFS (Perfect Forward Secrecy)

bind_forward:
  - zone_name: dn42
    forwarders: [fd42:d42:d42:53::1, fd42:d42:d42:54::1]
  - zone_name: 20.172.in-addr.arpa
    forwarders: [fd42:d42:d42:53::1, fd42:d42:d42:54::1]
  - zone_name: 21.172.in-addr.arpa
    forwarders: [fd42:d42:d42:53::1, fd42:d42:d42:54::1]
  - zone_name: 22.172.in-addr.arpa
    forwarders: [fd42:d42:d42:53::1, fd42:d42:d42:54::1]
  - zone_name: 23.172.in-addr.arpa
    forwarders: [fd42:d42:d42:53::1, fd42:d42:d42:54::1]
  - zone_name: 10.in-addr.arpa
    forwarders: [fd42:d42:d42:53::1, fd42:d42:d42:54::1]
  - zone_name: d.f.ip6.arpa
    forwarders: [fd42:d42:d42:53::1, fd42:d42:d42:54::1]
bind_listen_on: [any]
bind_listen_on_v6: [any]
bind_dnssec_validation: auto
bind_empty_zones_enable: "no"
bind_validate_except:
  - dn42
  - 20.172.in-addr.arpa
  - 21.172.in-addr.arpa
  - 22.172.in-addr.arpa
  - 23.172.in-addr.arpa
  - 10.in-addr.arpa
  - d.f.ip6.arpa
