---
bind_forward:
  - zone_name: dn42
    forwarders: [ "fd42:d42:d42:53::1", "fd42:d42:d42:54::1" ]
  - zone_name: 20.172.in-addr.arpa
    forwarders: [ "fd42:d42:d42:53::1", "fd42:d42:d42:54::1" ]
  - zone_name: 21.172.in-addr.arpa
    forwarders: [ "fd42:d42:d42:53::1", "fd42:d42:d42:54::1" ]
  - zone_name: 22.172.in-addr.arpa
    forwarders: [ "fd42:d42:d42:53::1", "fd42:d42:d42:54::1" ]
  - zone_name: 23.172.in-addr.arpa
    forwarders: [ "fd42:d42:d42:53::1", "fd42:d42:d42:54::1" ]
  - zone_name: 10.in-addr.arpa
    forwarders: [ "fd42:d42:d42:53::1", "fd42:d42:d42:54::1" ]
  - zone_name: d.f.ip6.arpa
    forwarders: [ "fd42:d42:d42:53::1", "fd42:d42:d42:54::1" ]
